services:
  db:
    image: mysql/mysql-server:latest
    container_name: estacionamento-mysql
    environment:
      MYSQL_DATABASE: estacionamentodb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - db
networks:
  spring-boot-mysql-network:
    driver: bridge
volumes:
  mysql-volume:
